# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util
from swagger_server.models.conflict_detail import ConflictDetail


class ApiResponseConflict(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, type: str=None, message: str=None, details: List[ConflictDetail]=None):  # noqa: E501
        """ApiResponseConflict - a model defined in Swagger

        :param code: The code of this ApiResponseConflict.  # noqa: E501
        :type code: int
        :param type: The type of this ApiResponseConflict.  # noqa: E501
        :type type: str
        :param message: The message of this ApiResponseConflict.  # noqa: E501
        :type message: str
        :param details: The details of this ApiResponseConflict.  # noqa: E501
        :type details: List[ConflictDetail]
        """
        self.swagger_types = {
            'code': int,
            'type': str,
            'message': str,
            'details': List[ConflictDetail]
        }

        self.attribute_map = {
            'code': 'code',
            'type': 'type',
            'message': 'message',
            'details': 'details'
        }

        self._code = code
        self._type = type
        self._message = message
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'ApiResponseConflict':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiResponseConflict of this ApiResponseConflict.  # noqa: E501
        :rtype: ApiResponseConflict
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this ApiResponseConflict.


        :return: The code of this ApiResponseConflict.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this ApiResponseConflict.


        :param code: The code of this ApiResponseConflict.
        :type code: int
        """

        self._code = code

    @property
    def type(self) -> str:
        """Gets the type of this ApiResponseConflict.


        :return: The type of this ApiResponseConflict.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ApiResponseConflict.


        :param type: The type of this ApiResponseConflict.
        :type type: str
        """

        self._type = type

    @property
    def message(self) -> str:
        """Gets the message of this ApiResponseConflict.


        :return: The message of this ApiResponseConflict.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ApiResponseConflict.


        :param message: The message of this ApiResponseConflict.
        :type message: str
        """

        self._message = message

    @property
    def details(self) -> List[ConflictDetail]:
        """Gets the details of this ApiResponseConflict.


        :return: The details of this ApiResponseConflict.
        :rtype: List[ConflictDetail]
        """
        return self._details

    @details.setter
    def details(self, details: List[ConflictDetail]):
        """Sets the details of this ApiResponseConflict.


        :param details: The details of this ApiResponseConflict.
        :type details: List[ConflictDetail]
        """

        self._details = details
