/**
 * Swagger Vacation calendar
 * This is Vacarion Calendar API description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: w.kostyukova@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Employee } from './employee';
import { LeaveDays } from './leaveDays';


export interface LeaveDaysEx { 
    id?: number;
    employeeId: number;
    leaveDays: number;
    startDate: string;
    endDate: string;
    employee?: Employee;
}
