---
swagger: "2.0"
info:
  description: "This is Vacarion Calendar API description"
  version: "1.0.0"
  title: "Swagger Vacation calendar"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "w.kostyukova@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/vcalendar"
tags:
- name: "employee"
  description: "Employee management"
- name: "user"
  description: "User management"
schemes:
- "https"
- "http"
paths:
  /employee:
    post:
      tags:
      - "employee"
      summary: "Add a new employee to the system. Role write:employees must be granted"
      description: ""
      operationId: "add_employee"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Employee object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Employee"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Employee"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiResponse"
        "409":
          description: "Employee already exists conflict"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
  /employee/findAll:
    get:
      tags:
      - "employee"
      summary: "Returns all Employees registered in the system."
      description: ""
      operationId: "find_all_employee"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Employee"
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
  /employee/findBy:
    get:
      tags:
      - "employee"
      summary: "Finds Employees by given parameters"
      description: ""
      operationId: "find_employees_by"
      produces:
      - "application/json"
      parameters:
      - name: "full_name"
        in: "query"
        description: "Full name template to filter by"
        required: false
        type: "string"
      - name: "position"
        in: "query"
        description: "Position template to filter by"
        required: false
        type: "string"
      - name: "specialization"
        in: "query"
        description: "Specialization template to filter by"
        required: false
        type: "string"
      - name: "expert"
        in: "query"
        description: "Expert mark to filter by"
        required: false
        type: "boolean"
      - name: "team_number"
        in: "query"
        description: "Team number to filter by"
        required: false
        type: "integer"
        format: "int32"
      - name: "email"
        in: "query"
        description: "Email template to filter by"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Employee"
        "400":
          description: "Invalid team number value"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
  /employee/findByEmail/{email}:
    get:
      tags:
      - "employee"
      summary: "Finds Employee by given email"
      description: ""
      operationId: "find_employee_by_email"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "path"
        description: "Unique employee email"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Employee"
        "404":
          description: "Employee not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
  /employee/{employeeId}:
    get:
      tags:
      - "employee"
      summary: "Find employee by ID"
      description: "Returns a single employee."
      operationId: "get_employee_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "employeeId"
        in: "path"
        description: "ID of empoyee to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Employee"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Employee not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
    put:
      tags:
      - "employee"
      summary: "Updates an employee in the system with form data. Role write:employees\
        \ must be granted"
      description: ""
      operationId: "update_employee_by_id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "employeeId"
        in: "path"
        description: "ID of empoyee to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Employee object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Employee"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Employee"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Employee not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiResponse"
        "409":
          description: "Employee already exists conflict"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
    delete:
      tags:
      - "employee"
      summary: "Deletes an employee. Role write:employees must be granteds"
      description: ""
      operationId: "delete_employee"
      produces:
      - "application/json"
      parameters:
      - name: "employeeId"
        in: "path"
        description: "Employee id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "Successful deletion"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Employee not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.employee_controller"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "Role write:users role must be granted"
      operationId: "create_user"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/User"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "409":
          description: "User already exists conflict"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/authenticate:
    get:
      tags:
      - "user"
      summary: "Generates token for an user"
      description: ""
      operationId: "authenticate_user"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid username/password supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/{username}:
    get:
      tags:
      - "user"
      summary: "Get user by user name. Role read:users role must be granted"
      description: ""
      operationId: "get_user_by_name"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be fetched. "
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid username supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "User not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    put:
      tags:
      - "user"
      summary: "Updated user"
      description: "This can only be done by with write:users role."
      operationId: "update_user"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid user supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "User not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      description: "This can only be done with write:users role."
      operationId: "delete_user"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        "204":
          description: "Successful deletion"
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: "Invalid username supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "User not found"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
  /user/findAll:
    get:
      tags:
      - "user"
      summary: "Finds all users. Role read:users role must be granted"
      description: ""
      operationId: "find_all_user"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        "403":
          description: "Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
      security:
      - Bearer: []
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
        example: "user"
      email:
        type: "string"
        example: "user@mail.com"
      password:
        type: "string"
        example: "123qwe"
      roles:
        type: "string"
        example: "write:employees"
    xml:
      name: "User"
    example:
      password: "123qwe"
      roles: "write:employees"
      id: 0
      email: "user@mail.com"
      username: "user"
  Employee:
    type: "object"
    required:
    - "email"
    - "expert"
    - "full_name"
    - "position"
    - "team_number"
    properties:
      employee_id:
        type: "integer"
        format: "int64"
      full_name:
        type: "string"
        example: "Joe Smith"
      position:
        type: "string"
        description: "Employee position"
        enum:
        - "junior engineer"
        - "senior engineer"
        - "chief engineer"
        - "team leader"
      specialization:
        type: "string"
        example: "Core"
        description: "Employee specialization, comma separated value form set(BA,\
          \ OACI, O365, Core)"
      team_number:
        type: "integer"
        format: "int32"
        example: 1
      expert:
        type: "boolean"
      email:
        type: "string"
        example: "joe@mail.com"
      leave_days_total:
        type: "integer"
        format: "int32"
      leave_days_left:
        type: "integer"
        format: "int32"
    xml:
      name: "Employee"
    example:
      expert: true
      full_name: "Joe Smith"
      employee_id: 0
      specialization: "Core"
      leave_days_left: 1
      team_number: 1
      position: "junior engineer"
      leave_days_total: 6
      email: "joe@mail.com"
  LeaveDays:
    type: "object"
    properties:
      leave_days:
        type: "integer"
        format: "int32"
      start_date:
        type: "string"
      end_date:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
