# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LeaveDays(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, leave_days: int=None, start_date: str=None, end_date: str=None):  # noqa: E501
        """LeaveDays - a model defined in Swagger

        :param leave_days: The leave_days of this LeaveDays.  # noqa: E501
        :type leave_days: int
        :param start_date: The start_date of this LeaveDays.  # noqa: E501
        :type start_date: str
        :param end_date: The end_date of this LeaveDays.  # noqa: E501
        :type end_date: str
        """
        self.swagger_types = {
            'leave_days': int,
            'start_date': str,
            'end_date': str
        }

        self.attribute_map = {
            'leave_days': 'leave_days',
            'start_date': 'start_date',
            'end_date': 'end_date'
        }

        self._leave_days = leave_days
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'LeaveDays':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LeaveDays of this LeaveDays.  # noqa: E501
        :rtype: LeaveDays
        """
        return util.deserialize_model(dikt, cls)

    @property
    def leave_days(self) -> int:
        """Gets the leave_days of this LeaveDays.


        :return: The leave_days of this LeaveDays.
        :rtype: int
        """
        return self._leave_days

    @leave_days.setter
    def leave_days(self, leave_days: int):
        """Sets the leave_days of this LeaveDays.


        :param leave_days: The leave_days of this LeaveDays.
        :type leave_days: int
        """

        self._leave_days = leave_days

    @property
    def start_date(self) -> str:
        """Gets the start_date of this LeaveDays.


        :return: The start_date of this LeaveDays.
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: str):
        """Sets the start_date of this LeaveDays.


        :param start_date: The start_date of this LeaveDays.
        :type start_date: str
        """

        self._start_date = start_date

    @property
    def end_date(self) -> str:
        """Gets the end_date of this LeaveDays.


        :return: The end_date of this LeaveDays.
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: str):
        """Sets the end_date of this LeaveDays.


        :param end_date: The end_date of this LeaveDays.
        :type end_date: str
        """

        self._end_date = end_date
